version: "3.8"
services:
  dim-db:
    container_name: "cim-db"
    image: "postgres:14"
    environment:
      POSTGRES_USER: "dim"
      POSTGRES_PASSWORD: "dim"
      POSTGRES_DB: "dim"
    networks:
      - "dim"
    volumes:
      - "dim-data:/var/lib/postgresql/data"
    restart: "always"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
networks:
  dim:
    driver: "bridge"

volumes:
  dim-data:
    name: "dim-data"
