version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    #user: 1000:1000
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - "mongo-db-data:/data/db"
      - "mongo-db-data:/data/configdb"
volumes:
  mongo-db-data:
    name: "mongo-db-data"